version: '3.4'
services:
  mysql:
    image: mysql:8.0.31
    env_file:
      - ./env/mysql.env
    ports:
      - $MYSQL_PORT:3306
    volumes:
      - ./vols/mysql/data/:/var/lib/mysql/
    user: $UID:$UID
  adminer:
    image: adminer:4.7.8-standalone
    env_file:
      - ./env/adminer.env
    ports:
      - $ADMINER_PORT:8080
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - $MAILHOG_SMTP_PORT:1025
      - $MAILHOG_UI_PORT:8025 
  build:
    image: build
    build:
      context: ..
      dockerfile: ./prod/Dockerfiles/build.Dockerfile
    env_file:
      - ./env/app.env
  app:
    image: app
    depends_on: 
      - build
    build: 
      context: .
      dockerfile: ./Dockerfiles/app.Dockerfile
  static:
    image: static
    depends_on: 
      - build
    build: 
      context: .
      dockerfile: ./Dockerfiles/static.Dockerfile
  proxy:
    image: proxy
    build:
      context: .
      dockerfile: ./Dockerfiles/proxy.Dockerfile
    ports:
      - $PROXY_PORT:80
    env_file:
      - ./env/proxy.env
  