name: Docker Images
run-name: Docker Images (${{ github.sha }})
on: [push]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  Build-Docker-Images:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: make build
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker tag build:latest ghcr.io/viduni/sanmark-test/build:latest
      - run: docker tag app:latest ghcr.io/viduni/sanmark-test/app:latest
      - run: docker tag static:latest ghcr.io/viduni/sanmark-test/static:latest
      - run: docker tag proxy:latest ghcr.io/viduni/sanmark-test/proxy:latest
      - run: docker push ghcr.io/viduni/sanmark-test/build:latest
      - run: docker push ghcr.io/viduni/sanmark-test/app:latest
      - run: docker push ghcr.io/viduni/sanmark-test/static:latest
      - run: docker push ghcr.io/viduni/sanmark-test/proxy:latest