name: Docker Images
run-name: Docker Images (${{ github.sha }})
on: [push]
jobs:
  Build-Docker-Images:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: make build
  Push-Docker-Images:
    needs: Build-Docker-Images
    steps:
      - run: docker images